### ISSUE TITLE
Critical bugs

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/clean_lang_history#1]
If this is what created e.g. https://github.com/giellalt/lang-kal/commits/main_with_history_fixed then there are critical bugs:

- Commit dates are lost. Looks like all commits are from when the script was run.

- Commits have the runner as committer (with original committer as author).

- Authors list is wrong. At least my name is, so probably others are.

**Comment by albbas** [comment]
> If this is what created e.g. https://github.com/giellalt/lang-kal/commits/main_with_history_fixed then there are critical bugs:
> 
Thanks for the feedback!

I used gitk to get an overview of the git log and such. The main history view shows the correct commit dates, so I thought everything was fine and dandy.

![first-lang-kal](https://user-images.githubusercontent.com/75695/179479816-d46e5954-87d0-4270-b725-fe5b4418ab7e.png)

>     * Commit dates are lost. Looks like all commits are from when the script was run.
> 
>     * Commits have the runner as committer (with original committer as author).
> 
Now that you mention it, I see that the committer and author info are different.
![author-committer-lang-kal](https://user-images.githubusercontent.com/75695/179480449-2a2e7455-0fb3-4cd0-a6ae-0b772aeab7ec.png)

git filter-branch can be used to set committer name and date equal to the author ditto.

>     * Authors list is wrong. At least my name is, so probably others are.

I/We can fix the author info in svn2git-authors.txt, turn it into a [git mailmap](https://git-scm.com/docs/gitmailmap), and use `git filter-repo --mailmap my-mailmap` to correct the info in the repo.

I'm on vacation now, but can have a look at this when I'm back.

**Comment by snomos** [comment]
Commands to clean up history can be found here: https://github.com/giellalt/giella-core/issues/20#issuecomment-1135506061

**Comment by albbas** [comment]
All the above issues have been solved with the commits pushed today
